#include <stdint.h>

enum MAV_MODE_FLAG : uint8_t{
    MAV_MODE_FLAG_SAFETY_ARMED = 128,
    MAV_MODE_FLAG_MANUAL_INPUT_ENABLED = 64,
    MAV_MODE_FLAG_HIL_ENABLED = 32,
	MAV_MODE_FLAG_STABILIZE_ENABLED = 16,
    MAV_MODE_FLAG_GUIDED_ENABLED = 8,
    MAV_MODE_FLAG_AUTO_ENABLED = 4,
    MAV_MODE_FLAG_TEST_ENABLED = 2,
    MAV_MODE_FLAG_CUSTOM_MODE_ENABLED = 1,
};

enum MAV_STATE : uint8_t {
    MAV_STATE_UNINIT = 0,
    MAV_STATE_BOOT,
    MAV_STATE_CALIBRATING,
    MAV_STATE_STANDBY,
    MAV_STATE_ACTIVE,
    MAV_STATE_CRITICAL,
    MAV_STATE_EMERGENCY,
    MAV_STATE_POWEROFF,
    MAV_STATE_FLIGHT_TERMINATION,
};